/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Hostel360 API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { http } from './http';
export type StayRequestSource = typeof StayRequestSource[keyof typeof StayRequestSource];


export const StayRequestSource = {
  BOOKING: 'BOOKING',
  DIRECT: 'DIRECT',
} as const;

export type StayRequestCurrency = typeof StayRequestCurrency[keyof typeof StayRequestCurrency];


export const StayRequestCurrency = {
  EUR: 'EUR',
  RSD: 'RSD',
} as const;

export type StayRequestPaymentStatus = typeof StayRequestPaymentStatus[keyof typeof StayRequestPaymentStatus];


export const StayRequestPaymentStatus = {
  NOT_PAID: 'NOT_PAID',
  PARTLY_PAID: 'PARTLY_PAID',
  PAID: 'PAID',
} as const;

/**
 * Pass guestId for an existing guest, or guestName (and guestCountry) to create one.
 */
export interface StayRequest {
  roomId: number;
  guestId?: number;
  /**
     * @minLength 0
     * @maxLength 100
     */
  guestName?: string;
  /**
     * @minLength 0
     * @maxLength 60
     */
  guestCountry?: string;
  /**
     * @minimum 1
     * @maximum 2
     */
  people: number;
  longTerm: boolean;
  source?: StayRequestSource;
  checkIn: string;
  checkOut?: string;
  /** @minimum 0 */
  amount: number;
  currency: StayRequestCurrency;
  paymentStatus: StayRequestPaymentStatus;
  /**
     * @minLength 0
     * @maxLength 500
     */
  note?: string;
}

/**
 * @nullable
 */
export type StaySource = typeof StaySource[keyof typeof StaySource] | null;


export const StaySource = {
  BOOKING: 'BOOKING',
  DIRECT: 'DIRECT',
} as const;

export type StayCurrency = typeof StayCurrency[keyof typeof StayCurrency];


export const StayCurrency = {
  EUR: 'EUR',
  RSD: 'RSD',
} as const;

export type StayPaymentStatus = typeof StayPaymentStatus[keyof typeof StayPaymentStatus];


export const StayPaymentStatus = {
  NOT_PAID: 'NOT_PAID',
  PARTLY_PAID: 'PARTLY_PAID',
  PAID: 'PAID',
} as const;

export type StayStatus = typeof StayStatus[keyof typeof StayStatus];


export const StayStatus = {
  BOOKED: 'BOOKED',
  CHECKED_IN: 'CHECKED_IN',
  CHECKED_OUT: 'CHECKED_OUT',
  CANCELLED: 'CANCELLED',
} as const;

export interface StayRoom {
  id: number;
  number: number;
  name: string;
}

export interface StayGuest {
  id: number;
  name: string;
  /** @nullable */
  country?: string | null;
}

export interface Stay {
  id: number;
  room: StayRoom;
  guest: StayGuest;
  people: number;
  longTerm: boolean;
  /** @nullable */
  source?: StaySource;
  checkIn: string;
  /**
     * Exclusive end date; empty for an open-ended long-term stay
     * @nullable
     */
  checkOut?: string | null;
  /**
     * Short stays only
     * @nullable
     */
  nights?: number | null;
  amount: number;
  currency: StayCurrency;
  eurToRsd: number;
  /** Amount converted to EUR with the saved rate */
  amountEur: number;
  paymentStatus: StayPaymentStatus;
  status: StayStatus;
  /** @nullable */
  note?: string | null;
}

export interface Settings {
  /** @minLength 1 */
  hostelName: string;
  /** @minimum 0.0001 */
  eurToRsd: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  bookingCommission: number;
}

export type RoomRequestStatus = typeof RoomRequestStatus[keyof typeof RoomRequestStatus];


export const RoomRequestStatus = {
  AVAILABLE: 'AVAILABLE',
  NEEDS_CLEANING: 'NEEDS_CLEANING',
  TAKEN: 'TAKEN',
} as const;

export interface RoomRequest {
  /**
     * @minimum 1
     * @maximum 999
     */
  number: number;
  /**
     * @minLength 0
     * @maxLength 50
     */
  name: string;
  /**
     * @minimum 1
     * @maximum 2
     */
  floor: number;
  /**
     * @minimum 1
     * @maximum 2
     */
  capacity: number;
  longTerm: boolean;
  status: RoomRequestStatus;
  /**
     * @minLength 0
     * @maxLength 150
     */
  bookingType?: string;
}

export type RoomStatus = typeof RoomStatus[keyof typeof RoomStatus];


export const RoomStatus = {
  AVAILABLE: 'AVAILABLE',
  NEEDS_CLEANING: 'NEEDS_CLEANING',
  TAKEN: 'TAKEN',
} as const;

export interface Room {
  id: number;
  number: number;
  name: string;
  floor: number;
  capacity: number;
  longTerm: boolean;
  status: RoomStatus;
  /** @nullable */
  bookingType?: string | null;
}

export interface GuestRequest {
  /**
     * @minLength 0
     * @maxLength 100
     */
  name: string;
  /**
     * @minLength 0
     * @maxLength 60
     */
  country?: string;
  /**
     * @minLength 0
     * @maxLength 500
     */
  note?: string;
}

export interface Guest {
  id: number;
  name: string;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  note?: string | null;
}

export interface RentPaymentRequest {
  stayId: number;
  month: string;
  paid: boolean;
}

export type ExpenseRequestCategory = typeof ExpenseRequestCategory[keyof typeof ExpenseRequestCategory];


export const ExpenseRequestCategory = {
  CLEANING: 'CLEANING',
  LAUNDRY: 'LAUNDRY',
  REPAIRS: 'REPAIRS',
  ELECTRICITY: 'ELECTRICITY',
  WATER: 'WATER',
  HEATING: 'HEATING',
  INTERNET: 'INTERNET',
  GARBAGE: 'GARBAGE',
  STAFF: 'STAFF',
  TAXES: 'TAXES',
  EQUIPMENT: 'EQUIPMENT',
  OTHER: 'OTHER',
} as const;

export type ExpenseRequestCurrency = typeof ExpenseRequestCurrency[keyof typeof ExpenseRequestCurrency];


export const ExpenseRequestCurrency = {
  EUR: 'EUR',
  RSD: 'RSD',
} as const;

export interface ExpenseRequest {
  date: string;
  category: ExpenseRequestCategory;
  /** @minimum 0 */
  amount: number;
  currency: ExpenseRequestCurrency;
  /**
     * @minLength 0
     * @maxLength 500
     */
  note?: string;
  repeatMonthly: boolean;
}

export type ExpenseCategory = typeof ExpenseCategory[keyof typeof ExpenseCategory];


export const ExpenseCategory = {
  CLEANING: 'CLEANING',
  LAUNDRY: 'LAUNDRY',
  REPAIRS: 'REPAIRS',
  ELECTRICITY: 'ELECTRICITY',
  WATER: 'WATER',
  HEATING: 'HEATING',
  INTERNET: 'INTERNET',
  GARBAGE: 'GARBAGE',
  STAFF: 'STAFF',
  TAXES: 'TAXES',
  EQUIPMENT: 'EQUIPMENT',
  OTHER: 'OTHER',
} as const;

export type ExpenseCurrency = typeof ExpenseCurrency[keyof typeof ExpenseCurrency];


export const ExpenseCurrency = {
  EUR: 'EUR',
  RSD: 'RSD',
} as const;

export interface Expense {
  id: number;
  date: string;
  category: ExpenseCategory;
  amount: number;
  currency: ExpenseCurrency;
  eurToRsd: number;
  amountEur: number;
  /** @nullable */
  note?: string | null;
  repeatMonthly: boolean;
  /**
     * First day of the last month a repeating expense counts in
     * @nullable
     */
  repeatUntil?: string | null;
}

export interface BookingImportResult {
  imported: number;
  alreadyInApp: number;
  notImported: number;
  /** Stays ended early because the next guest got the room */
  shortened: string[];
  /** Reservations that could not be imported */
  problems: string[];
}

export interface LoginRequest {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
}

export interface TokenResponse {
  token: string;
  expiresAt: string;
}

export type RoomStatusRequestStatus = typeof RoomStatusRequestStatus[keyof typeof RoomStatusRequestStatus];


export const RoomStatusRequestStatus = {
  AVAILABLE: 'AVAILABLE',
  NEEDS_CLEANING: 'NEEDS_CLEANING',
  TAKEN: 'TAKEN',
} as const;

export interface RoomStatusRequest {
  status: RoomStatusRequestStatus;
}

export type CategoryTotalCategory = typeof CategoryTotalCategory[keyof typeof CategoryTotalCategory];


export const CategoryTotalCategory = {
  CLEANING: 'CLEANING',
  LAUNDRY: 'LAUNDRY',
  REPAIRS: 'REPAIRS',
  ELECTRICITY: 'ELECTRICITY',
  WATER: 'WATER',
  HEATING: 'HEATING',
  INTERNET: 'INTERNET',
  GARBAGE: 'GARBAGE',
  STAFF: 'STAFF',
  TAXES: 'TAXES',
  EQUIPMENT: 'EQUIPMENT',
  OTHER: 'OTHER',
} as const;

export interface CategoryTotal {
  category: CategoryTotalCategory;
  amount: number;
}

/**
 * Income counts on the arrival date; long-term rent counts once per month.
 */
export interface MonthSummary {
  /** First day of the month */
  month: string;
  booking: number;
  direct: number;
  longTerm: number;
  income: number;
  commission: number;
  expenses: number;
  costs: number;
  profit: number;
  /** Expenses by category, largest first */
  byCategory: CategoryTotal[];
  arrivals: number;
}

export type UnpaidItemCurrency = typeof UnpaidItemCurrency[keyof typeof UnpaidItemCurrency];


export const UnpaidItemCurrency = {
  EUR: 'EUR',
  RSD: 'RSD',
} as const;

/**
 * Short stays only
 * @nullable
 */
export type UnpaidItemPaymentStatus = typeof UnpaidItemPaymentStatus[keyof typeof UnpaidItemPaymentStatus] | null;


export const UnpaidItemPaymentStatus = {
  NOT_PAID: 'NOT_PAID',
  PARTLY_PAID: 'PARTLY_PAID',
  PAID: 'PAID',
} as const;

/**
 * A short stay not fully paid, or one unpaid month of a long-term stay
 */
export interface UnpaidItem {
  stayId: number;
  guestName: string;
  roomNumber: number;
  roomName: string;
  longTerm: boolean;
  checkIn: string;
  /** @nullable */
  checkOut?: string | null;
  /**
     * Rent month (first day) for long-term stays
     * @nullable
     */
  month?: string | null;
  amount: number;
  currency: UnpaidItemCurrency;
  amountEur: number;
  /**
     * Short stays only
     * @nullable
     */
  paymentStatus?: UnpaidItemPaymentStatus;
}

export type ListStaysParams = {
from?: string;
to?: string;
guestId?: number;
};

export type ImportBookingBody = {
  file: Blob | File;
};

export type ListGuestsParams = {
q?: string;
};

export type ListExpensesParams = {
month: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getStay = (
    id: number,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Stay>(
      {url: `/api/stays/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetStayQueryKey = (id: number,) => {
    return [
    `/api/stays/${id}`
    ] as const;
    }


export const getGetStayQueryOptions = <TData = Awaited<ReturnType<typeof getStay>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStay>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStayQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStay>>> = ({ signal }) => getStay(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStay>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStayQueryResult = NonNullable<Awaited<ReturnType<typeof getStay>>>
export type GetStayQueryError = unknown


export function useGetStay<TData = Awaited<ReturnType<typeof getStay>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStay>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStay>>,
          TError,
          Awaited<ReturnType<typeof getStay>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStay<TData = Awaited<ReturnType<typeof getStay>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStay>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStay>>,
          TError,
          Awaited<ReturnType<typeof getStay>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStay<TData = Awaited<ReturnType<typeof getStay>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStay>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetStay<TData = Awaited<ReturnType<typeof getStay>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStay>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStayQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const updateStay = (
    id: number,
    stayRequest: StayRequest,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Stay>(
      {url: `/api/stays/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: stayRequest, signal
    },
      options);
    }




export const getUpdateStayMutationKey = () => ['updateStay'] as const;

export const getUpdateStayMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStay>>, TError,UpdateStayMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof updateStay>>, TError,UpdateStayMutationVariables, TContext> => {

const mutationKey = getUpdateStayMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStay>>, UpdateStayMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateStay(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateStayMutationResult = NonNullable<Awaited<ReturnType<typeof updateStay>>>
    export type UpdateStayMutationBody = StayRequest
    export type UpdateStayMutationError = unknown
    export type UpdateStayMutationVariables = {id: number;data: StayRequest}

    export const useUpdateStay = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStay>>, TError,UpdateStayMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStay>>,
        TError,
        UpdateStayMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateStayMutationOptions(options), queryClient);
    }

export const deleteStay = (
    id: number,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<void>(
      {url: `/api/stays/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteStayMutationKey = () => ['deleteStay'] as const;

export const getDeleteStayMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStay>>, TError,DeleteStayMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteStay>>, TError,DeleteStayMutationVariables, TContext> => {

const mutationKey = getDeleteStayMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteStay>>, DeleteStayMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteStay(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteStayMutationResult = NonNullable<Awaited<ReturnType<typeof deleteStay>>>

    export type DeleteStayMutationError = unknown
    export type DeleteStayMutationVariables = {id: number}

    export const useDeleteStay = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStay>>, TError,DeleteStayMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteStay>>,
        TError,
        DeleteStayMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteStayMutationOptions(options), queryClient);
    }

export const getSettings = (

 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Settings>(
      {url: `/api/settings`, method: 'GET', signal
    },
      options);
    }




export const getGetSettingsQueryKey = () => {
    return [
    `/api/settings`
    ] as const;
    }


export const getGetSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSettings>>> = ({ signal }) => getSettings(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getSettings>>>
export type GetSettingsQueryError = unknown


export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettings>>,
          TError,
          Awaited<ReturnType<typeof getSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettings>>,
          TError,
          Awaited<ReturnType<typeof getSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const updateSettings = (
    settings: Settings,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Settings>(
      {url: `/api/settings`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: settings, signal
    },
      options);
    }




export const getUpdateSettingsMutationKey = () => ['updateSettings'] as const;

export const getUpdateSettingsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSettings>>, TError,UpdateSettingsMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSettings>>, TError,UpdateSettingsMutationVariables, TContext> => {

const mutationKey = getUpdateSettingsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSettings>>, UpdateSettingsMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  updateSettings(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof updateSettings>>>
    export type UpdateSettingsMutationBody = Settings
    export type UpdateSettingsMutationError = unknown
    export type UpdateSettingsMutationVariables = {data: Settings}

    export const useUpdateSettings = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSettings>>, TError,UpdateSettingsMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSettings>>,
        TError,
        UpdateSettingsMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateSettingsMutationOptions(options), queryClient);
    }

export const getRoom = (
    id: number,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Room>(
      {url: `/api/rooms/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetRoomQueryKey = (id: number,) => {
    return [
    `/api/rooms/${id}`
    ] as const;
    }


export const getGetRoomQueryOptions = <TData = Awaited<ReturnType<typeof getRoom>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoom>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRoomQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoom>>> = ({ signal }) => getRoom(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRoom>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRoomQueryResult = NonNullable<Awaited<ReturnType<typeof getRoom>>>
export type GetRoomQueryError = unknown


export function useGetRoom<TData = Awaited<ReturnType<typeof getRoom>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoom>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoom>>,
          TError,
          Awaited<ReturnType<typeof getRoom>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoom<TData = Awaited<ReturnType<typeof getRoom>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoom>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoom>>,
          TError,
          Awaited<ReturnType<typeof getRoom>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoom<TData = Awaited<ReturnType<typeof getRoom>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoom>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetRoom<TData = Awaited<ReturnType<typeof getRoom>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoom>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRoomQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const updateRoom = (
    id: number,
    roomRequest: RoomRequest,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Room>(
      {url: `/api/rooms/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: roomRequest, signal
    },
      options);
    }




export const getUpdateRoomMutationKey = () => ['updateRoom'] as const;

export const getUpdateRoomMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRoom>>, TError,UpdateRoomMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof updateRoom>>, TError,UpdateRoomMutationVariables, TContext> => {

const mutationKey = getUpdateRoomMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRoom>>, UpdateRoomMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateRoom(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateRoomMutationResult = NonNullable<Awaited<ReturnType<typeof updateRoom>>>
    export type UpdateRoomMutationBody = RoomRequest
    export type UpdateRoomMutationError = unknown
    export type UpdateRoomMutationVariables = {id: number;data: RoomRequest}

    export const useUpdateRoom = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRoom>>, TError,UpdateRoomMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRoom>>,
        TError,
        UpdateRoomMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateRoomMutationOptions(options), queryClient);
    }

export const deleteRoom = (
    id: number,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<void>(
      {url: `/api/rooms/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteRoomMutationKey = () => ['deleteRoom'] as const;

export const getDeleteRoomMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRoom>>, TError,DeleteRoomMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRoom>>, TError,DeleteRoomMutationVariables, TContext> => {

const mutationKey = getDeleteRoomMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRoom>>, DeleteRoomMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteRoom(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteRoomMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRoom>>>

    export type DeleteRoomMutationError = unknown
    export type DeleteRoomMutationVariables = {id: number}

    export const useDeleteRoom = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRoom>>, TError,DeleteRoomMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRoom>>,
        TError,
        DeleteRoomMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteRoomMutationOptions(options), queryClient);
    }

export const getGuest = (
    id: number,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Guest>(
      {url: `/api/guests/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetGuestQueryKey = (id: number,) => {
    return [
    `/api/guests/${id}`
    ] as const;
    }


export const getGetGuestQueryOptions = <TData = Awaited<ReturnType<typeof getGuest>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuest>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGuestQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGuest>>> = ({ signal }) => getGuest(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGuest>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGuestQueryResult = NonNullable<Awaited<ReturnType<typeof getGuest>>>
export type GetGuestQueryError = unknown


export function useGetGuest<TData = Awaited<ReturnType<typeof getGuest>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuest>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGuest>>,
          TError,
          Awaited<ReturnType<typeof getGuest>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGuest<TData = Awaited<ReturnType<typeof getGuest>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuest>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGuest>>,
          TError,
          Awaited<ReturnType<typeof getGuest>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGuest<TData = Awaited<ReturnType<typeof getGuest>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuest>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGuest<TData = Awaited<ReturnType<typeof getGuest>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuest>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGuestQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const updateGuest = (
    id: number,
    guestRequest: GuestRequest,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Guest>(
      {url: `/api/guests/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: guestRequest, signal
    },
      options);
    }




export const getUpdateGuestMutationKey = () => ['updateGuest'] as const;

export const getUpdateGuestMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGuest>>, TError,UpdateGuestMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof updateGuest>>, TError,UpdateGuestMutationVariables, TContext> => {

const mutationKey = getUpdateGuestMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateGuest>>, UpdateGuestMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateGuest(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateGuestMutationResult = NonNullable<Awaited<ReturnType<typeof updateGuest>>>
    export type UpdateGuestMutationBody = GuestRequest
    export type UpdateGuestMutationError = unknown
    export type UpdateGuestMutationVariables = {id: number;data: GuestRequest}

    export const useUpdateGuest = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGuest>>, TError,UpdateGuestMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateGuest>>,
        TError,
        UpdateGuestMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateGuestMutationOptions(options), queryClient);
    }

export const deleteGuest = (
    id: number,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<void>(
      {url: `/api/guests/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteGuestMutationKey = () => ['deleteGuest'] as const;

export const getDeleteGuestMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGuest>>, TError,DeleteGuestMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteGuest>>, TError,DeleteGuestMutationVariables, TContext> => {

const mutationKey = getDeleteGuestMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteGuest>>, DeleteGuestMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteGuest(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteGuestMutationResult = NonNullable<Awaited<ReturnType<typeof deleteGuest>>>

    export type DeleteGuestMutationError = unknown
    export type DeleteGuestMutationVariables = {id: number}

    export const useDeleteGuest = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGuest>>, TError,DeleteGuestMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteGuest>>,
        TError,
        DeleteGuestMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteGuestMutationOptions(options), queryClient);
    }

export const setRentPaid = (
    rentPaymentRequest: RentPaymentRequest,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<void>(
      {url: `/api/finance/rent-payments`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: rentPaymentRequest, signal
    },
      options);
    }




export const getSetRentPaidMutationKey = () => ['setRentPaid'] as const;

export const getSetRentPaidMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setRentPaid>>, TError,SetRentPaidMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof setRentPaid>>, TError,SetRentPaidMutationVariables, TContext> => {

const mutationKey = getSetRentPaidMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setRentPaid>>, SetRentPaidMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  setRentPaid(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetRentPaidMutationResult = NonNullable<Awaited<ReturnType<typeof setRentPaid>>>
    export type SetRentPaidMutationBody = RentPaymentRequest
    export type SetRentPaidMutationError = unknown
    export type SetRentPaidMutationVariables = {data: RentPaymentRequest}

    export const useSetRentPaid = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setRentPaid>>, TError,SetRentPaidMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setRentPaid>>,
        TError,
        SetRentPaidMutationVariables,
        TContext
      > => {
      return useMutation(getSetRentPaidMutationOptions(options), queryClient);
    }

export const updateExpense = (
    id: number,
    expenseRequest: ExpenseRequest,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Expense>(
      {url: `/api/expenses/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: expenseRequest, signal
    },
      options);
    }




export const getUpdateExpenseMutationKey = () => ['updateExpense'] as const;

export const getUpdateExpenseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateExpense>>, TError,UpdateExpenseMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof updateExpense>>, TError,UpdateExpenseMutationVariables, TContext> => {

const mutationKey = getUpdateExpenseMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateExpense>>, UpdateExpenseMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateExpense(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateExpenseMutationResult = NonNullable<Awaited<ReturnType<typeof updateExpense>>>
    export type UpdateExpenseMutationBody = ExpenseRequest
    export type UpdateExpenseMutationError = unknown
    export type UpdateExpenseMutationVariables = {id: number;data: ExpenseRequest}

    export const useUpdateExpense = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateExpense>>, TError,UpdateExpenseMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateExpense>>,
        TError,
        UpdateExpenseMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateExpenseMutationOptions(options), queryClient);
    }

export const deleteExpense = (
    id: number,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<void>(
      {url: `/api/expenses/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteExpenseMutationKey = () => ['deleteExpense'] as const;

export const getDeleteExpenseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteExpense>>, TError,DeleteExpenseMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteExpense>>, TError,DeleteExpenseMutationVariables, TContext> => {

const mutationKey = getDeleteExpenseMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteExpense>>, DeleteExpenseMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteExpense(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteExpenseMutationResult = NonNullable<Awaited<ReturnType<typeof deleteExpense>>>

    export type DeleteExpenseMutationError = unknown
    export type DeleteExpenseMutationVariables = {id: number}

    export const useDeleteExpense = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteExpense>>, TError,DeleteExpenseMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteExpense>>,
        TError,
        DeleteExpenseMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteExpenseMutationOptions(options), queryClient);
    }

export const listStays = (
    params?: ListStaysParams,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Stay[]>(
      {url: `/api/stays`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListStaysQueryKey = (params?: ListStaysParams,) => {
    return [
    `/api/stays`, ...(params ? [params] : [])
    ] as const;
    }


export const getListStaysQueryOptions = <TData = Awaited<ReturnType<typeof listStays>>, TError = unknown>(params?: ListStaysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStays>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStaysQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStays>>> = ({ signal }) => listStays(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStays>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStaysQueryResult = NonNullable<Awaited<ReturnType<typeof listStays>>>
export type ListStaysQueryError = unknown


export function useListStays<TData = Awaited<ReturnType<typeof listStays>>, TError = unknown>(
 params: undefined |  ListStaysParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStays>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStays>>,
          TError,
          Awaited<ReturnType<typeof listStays>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStays<TData = Awaited<ReturnType<typeof listStays>>, TError = unknown>(
 params?: ListStaysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStays>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStays>>,
          TError,
          Awaited<ReturnType<typeof listStays>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStays<TData = Awaited<ReturnType<typeof listStays>>, TError = unknown>(
 params?: ListStaysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStays>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListStays<TData = Awaited<ReturnType<typeof listStays>>, TError = unknown>(
 params?: ListStaysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStays>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStaysQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const createStay = (
    stayRequest: StayRequest,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Stay>(
      {url: `/api/stays`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: stayRequest, signal
    },
      options);
    }




export const getCreateStayMutationKey = () => ['createStay'] as const;

export const getCreateStayMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStay>>, TError,CreateStayMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof createStay>>, TError,CreateStayMutationVariables, TContext> => {

const mutationKey = getCreateStayMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStay>>, CreateStayMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createStay(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateStayMutationResult = NonNullable<Awaited<ReturnType<typeof createStay>>>
    export type CreateStayMutationBody = StayRequest
    export type CreateStayMutationError = unknown
    export type CreateStayMutationVariables = {data: StayRequest}

    export const useCreateStay = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStay>>, TError,CreateStayMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createStay>>,
        TError,
        CreateStayMutationVariables,
        TContext
      > => {
      return useMutation(getCreateStayMutationOptions(options), queryClient);
    }

export const markPaid = (
    id: number,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Stay>(
      {url: `/api/stays/${id}/paid`, method: 'POST', signal
    },
      options);
    }




export const getMarkPaidMutationKey = () => ['markPaid'] as const;

export const getMarkPaidMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markPaid>>, TError,MarkPaidMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof markPaid>>, TError,MarkPaidMutationVariables, TContext> => {

const mutationKey = getMarkPaidMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markPaid>>, MarkPaidMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  markPaid(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MarkPaidMutationResult = NonNullable<Awaited<ReturnType<typeof markPaid>>>

    export type MarkPaidMutationError = unknown
    export type MarkPaidMutationVariables = {id: number}

    export const useMarkPaid = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markPaid>>, TError,MarkPaidMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markPaid>>,
        TError,
        MarkPaidMutationVariables,
        TContext
      > => {
      return useMutation(getMarkPaidMutationOptions(options), queryClient);
    }

export const checkOut = (
    id: number,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Stay>(
      {url: `/api/stays/${id}/check-out`, method: 'POST', signal
    },
      options);
    }




export const getCheckOutMutationKey = () => ['checkOut'] as const;

export const getCheckOutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkOut>>, TError,CheckOutMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof checkOut>>, TError,CheckOutMutationVariables, TContext> => {

const mutationKey = getCheckOutMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof checkOut>>, CheckOutMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  checkOut(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CheckOutMutationResult = NonNullable<Awaited<ReturnType<typeof checkOut>>>

    export type CheckOutMutationError = unknown
    export type CheckOutMutationVariables = {id: number}

    export const useCheckOut = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkOut>>, TError,CheckOutMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof checkOut>>,
        TError,
        CheckOutMutationVariables,
        TContext
      > => {
      return useMutation(getCheckOutMutationOptions(options), queryClient);
    }

export const checkIn = (
    id: number,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Stay>(
      {url: `/api/stays/${id}/check-in`, method: 'POST', signal
    },
      options);
    }




export const getCheckInMutationKey = () => ['checkIn'] as const;

export const getCheckInMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkIn>>, TError,CheckInMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof checkIn>>, TError,CheckInMutationVariables, TContext> => {

const mutationKey = getCheckInMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof checkIn>>, CheckInMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  checkIn(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CheckInMutationResult = NonNullable<Awaited<ReturnType<typeof checkIn>>>

    export type CheckInMutationError = unknown
    export type CheckInMutationVariables = {id: number}

    export const useCheckIn = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkIn>>, TError,CheckInMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof checkIn>>,
        TError,
        CheckInMutationVariables,
        TContext
      > => {
      return useMutation(getCheckInMutationOptions(options), queryClient);
    }

export const cancelStay = (
    id: number,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Stay>(
      {url: `/api/stays/${id}/cancel`, method: 'POST', signal
    },
      options);
    }




export const getCancelStayMutationKey = () => ['cancelStay'] as const;

export const getCancelStayMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelStay>>, TError,CancelStayMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof cancelStay>>, TError,CancelStayMutationVariables, TContext> => {

const mutationKey = getCancelStayMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelStay>>, CancelStayMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  cancelStay(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CancelStayMutationResult = NonNullable<Awaited<ReturnType<typeof cancelStay>>>

    export type CancelStayMutationError = unknown
    export type CancelStayMutationVariables = {id: number}

    export const useCancelStay = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelStay>>, TError,CancelStayMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelStay>>,
        TError,
        CancelStayMutationVariables,
        TContext
      > => {
      return useMutation(getCancelStayMutationOptions(options), queryClient);
    }

export const importBooking = (
    importBookingBody?: ImportBookingBody,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {

      const formData = new FormData();
if(importBookingBody?.file !== undefined) {
 formData.append(`file`, importBookingBody.file);
 }

      return http<BookingImportResult>(
      {url: `/api/stays/import-booking`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }




export const getImportBookingMutationKey = () => ['importBooking'] as const;

export const getImportBookingMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importBooking>>, TError,ImportBookingMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof importBooking>>, TError,ImportBookingMutationVariables, TContext> => {

const mutationKey = getImportBookingMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importBooking>>, ImportBookingMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  importBooking(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ImportBookingMutationResult = NonNullable<Awaited<ReturnType<typeof importBooking>>>
    export type ImportBookingMutationBody = ImportBookingBody | undefined
    export type ImportBookingMutationError = unknown
    export type ImportBookingMutationVariables = {data?: ImportBookingBody}

    export const useImportBooking = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importBooking>>, TError,ImportBookingMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importBooking>>,
        TError,
        ImportBookingMutationVariables,
        TContext
      > => {
      return useMutation(getImportBookingMutationOptions(options), queryClient);
    }

export const listRooms = (

 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Room[]>(
      {url: `/api/rooms`, method: 'GET', signal
    },
      options);
    }




export const getListRoomsQueryKey = () => {
    return [
    `/api/rooms`
    ] as const;
    }


export const getListRoomsQueryOptions = <TData = Awaited<ReturnType<typeof listRooms>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRooms>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRoomsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRooms>>> = ({ signal }) => listRooms(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRooms>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRoomsQueryResult = NonNullable<Awaited<ReturnType<typeof listRooms>>>
export type ListRoomsQueryError = unknown


export function useListRooms<TData = Awaited<ReturnType<typeof listRooms>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRooms>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRooms>>,
          TError,
          Awaited<ReturnType<typeof listRooms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRooms<TData = Awaited<ReturnType<typeof listRooms>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRooms>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRooms>>,
          TError,
          Awaited<ReturnType<typeof listRooms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRooms<TData = Awaited<ReturnType<typeof listRooms>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRooms>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListRooms<TData = Awaited<ReturnType<typeof listRooms>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRooms>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRoomsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const createRoom = (
    roomRequest: RoomRequest,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Room>(
      {url: `/api/rooms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: roomRequest, signal
    },
      options);
    }




export const getCreateRoomMutationKey = () => ['createRoom'] as const;

export const getCreateRoomMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRoom>>, TError,CreateRoomMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof createRoom>>, TError,CreateRoomMutationVariables, TContext> => {

const mutationKey = getCreateRoomMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRoom>>, CreateRoomMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createRoom(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateRoomMutationResult = NonNullable<Awaited<ReturnType<typeof createRoom>>>
    export type CreateRoomMutationBody = RoomRequest
    export type CreateRoomMutationError = unknown
    export type CreateRoomMutationVariables = {data: RoomRequest}

    export const useCreateRoom = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRoom>>, TError,CreateRoomMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRoom>>,
        TError,
        CreateRoomMutationVariables,
        TContext
      > => {
      return useMutation(getCreateRoomMutationOptions(options), queryClient);
    }

export const listGuests = (
    params?: ListGuestsParams,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Guest[]>(
      {url: `/api/guests`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListGuestsQueryKey = (params?: ListGuestsParams,) => {
    return [
    `/api/guests`, ...(params ? [params] : [])
    ] as const;
    }


export const getListGuestsQueryOptions = <TData = Awaited<ReturnType<typeof listGuests>>, TError = unknown>(params?: ListGuestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGuests>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGuestsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGuests>>> = ({ signal }) => listGuests(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGuests>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGuestsQueryResult = NonNullable<Awaited<ReturnType<typeof listGuests>>>
export type ListGuestsQueryError = unknown


export function useListGuests<TData = Awaited<ReturnType<typeof listGuests>>, TError = unknown>(
 params: undefined |  ListGuestsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGuests>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGuests>>,
          TError,
          Awaited<ReturnType<typeof listGuests>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGuests<TData = Awaited<ReturnType<typeof listGuests>>, TError = unknown>(
 params?: ListGuestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGuests>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGuests>>,
          TError,
          Awaited<ReturnType<typeof listGuests>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGuests<TData = Awaited<ReturnType<typeof listGuests>>, TError = unknown>(
 params?: ListGuestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGuests>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListGuests<TData = Awaited<ReturnType<typeof listGuests>>, TError = unknown>(
 params?: ListGuestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGuests>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGuestsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const createGuest = (
    guestRequest: GuestRequest,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Guest>(
      {url: `/api/guests`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: guestRequest, signal
    },
      options);
    }




export const getCreateGuestMutationKey = () => ['createGuest'] as const;

export const getCreateGuestMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGuest>>, TError,CreateGuestMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof createGuest>>, TError,CreateGuestMutationVariables, TContext> => {

const mutationKey = getCreateGuestMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGuest>>, CreateGuestMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createGuest(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateGuestMutationResult = NonNullable<Awaited<ReturnType<typeof createGuest>>>
    export type CreateGuestMutationBody = GuestRequest
    export type CreateGuestMutationError = unknown
    export type CreateGuestMutationVariables = {data: GuestRequest}

    export const useCreateGuest = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGuest>>, TError,CreateGuestMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createGuest>>,
        TError,
        CreateGuestMutationVariables,
        TContext
      > => {
      return useMutation(getCreateGuestMutationOptions(options), queryClient);
    }

export const listExpenses = (
    params: ListExpensesParams,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Expense[]>(
      {url: `/api/expenses`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListExpensesQueryKey = (params?: ListExpensesParams,) => {
    return [
    `/api/expenses`, ...(params ? [params] : [])
    ] as const;
    }


export const getListExpensesQueryOptions = <TData = Awaited<ReturnType<typeof listExpenses>>, TError = unknown>(params: ListExpensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExpenses>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListExpensesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listExpenses>>> = ({ signal }) => listExpenses(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listExpenses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListExpensesQueryResult = NonNullable<Awaited<ReturnType<typeof listExpenses>>>
export type ListExpensesQueryError = unknown


export function useListExpenses<TData = Awaited<ReturnType<typeof listExpenses>>, TError = unknown>(
 params: ListExpensesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExpenses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExpenses>>,
          TError,
          Awaited<ReturnType<typeof listExpenses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListExpenses<TData = Awaited<ReturnType<typeof listExpenses>>, TError = unknown>(
 params: ListExpensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExpenses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExpenses>>,
          TError,
          Awaited<ReturnType<typeof listExpenses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListExpenses<TData = Awaited<ReturnType<typeof listExpenses>>, TError = unknown>(
 params: ListExpensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExpenses>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListExpenses<TData = Awaited<ReturnType<typeof listExpenses>>, TError = unknown>(
 params: ListExpensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExpenses>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListExpensesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const createExpense = (
    expenseRequest: ExpenseRequest,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Expense>(
      {url: `/api/expenses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: expenseRequest, signal
    },
      options);
    }




export const getCreateExpenseMutationKey = () => ['createExpense'] as const;

export const getCreateExpenseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createExpense>>, TError,CreateExpenseMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof createExpense>>, TError,CreateExpenseMutationVariables, TContext> => {

const mutationKey = getCreateExpenseMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createExpense>>, CreateExpenseMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createExpense(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateExpenseMutationResult = NonNullable<Awaited<ReturnType<typeof createExpense>>>
    export type CreateExpenseMutationBody = ExpenseRequest
    export type CreateExpenseMutationError = unknown
    export type CreateExpenseMutationVariables = {data: ExpenseRequest}

    export const useCreateExpense = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createExpense>>, TError,CreateExpenseMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createExpense>>,
        TError,
        CreateExpenseMutationVariables,
        TContext
      > => {
      return useMutation(getCreateExpenseMutationOptions(options), queryClient);
    }

export const stopRepeating = (
    id: number,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Expense>(
      {url: `/api/expenses/${id}/stop`, method: 'POST', signal
    },
      options);
    }




export const getStopRepeatingMutationKey = () => ['stopRepeating'] as const;

export const getStopRepeatingMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stopRepeating>>, TError,StopRepeatingMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof stopRepeating>>, TError,StopRepeatingMutationVariables, TContext> => {

const mutationKey = getStopRepeatingMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stopRepeating>>, StopRepeatingMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  stopRepeating(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StopRepeatingMutationResult = NonNullable<Awaited<ReturnType<typeof stopRepeating>>>

    export type StopRepeatingMutationError = unknown
    export type StopRepeatingMutationVariables = {id: number}

    export const useStopRepeating = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stopRepeating>>, TError,StopRepeatingMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stopRepeating>>,
        TError,
        StopRepeatingMutationVariables,
        TContext
      > => {
      return useMutation(getStopRepeatingMutationOptions(options), queryClient);
    }

export const login = (
    loginRequest: LoginRequest,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<TokenResponse>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }




export const getLoginMutationKey = () => ['login'] as const;

export const getLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,LoginMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,LoginMutationVariables, TContext> => {

const mutationKey = getLoginMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, LoginMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginRequest
    export type LoginMutationError = unknown
    export type LoginMutationVariables = {data: LoginRequest}

    export const useLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,LoginMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        LoginMutationVariables,
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }

export const updateRoomStatus = (
    id: number,
    roomStatusRequest: RoomStatusRequest,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<Room>(
      {url: `/api/rooms/${id}/status`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: roomStatusRequest, signal
    },
      options);
    }




export const getUpdateRoomStatusMutationKey = () => ['updateRoomStatus'] as const;

export const getUpdateRoomStatusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRoomStatus>>, TError,UpdateRoomStatusMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof updateRoomStatus>>, TError,UpdateRoomStatusMutationVariables, TContext> => {

const mutationKey = getUpdateRoomStatusMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRoomStatus>>, UpdateRoomStatusMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateRoomStatus(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateRoomStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateRoomStatus>>>
    export type UpdateRoomStatusMutationBody = RoomStatusRequest
    export type UpdateRoomStatusMutationError = unknown
    export type UpdateRoomStatusMutationVariables = {id: number;data: RoomStatusRequest}

    export const useUpdateRoomStatus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRoomStatus>>, TError,UpdateRoomStatusMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRoomStatus>>,
        TError,
        UpdateRoomStatusMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateRoomStatusMutationOptions(options), queryClient);
    }

export const financeYear = (
    year: number,
 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<MonthSummary[]>(
      {url: `/api/finance/year/${year}`, method: 'GET', signal
    },
      options);
    }




export const getFinanceYearQueryKey = (year: number,) => {
    return [
    `/api/finance/year/${year}`
    ] as const;
    }


export const getFinanceYearQueryOptions = <TData = Awaited<ReturnType<typeof financeYear>>, TError = unknown>(year: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof financeYear>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFinanceYearQueryKey(year);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof financeYear>>> = ({ signal }) => financeYear(year, requestOptions, signal);





   return  { queryKey, queryFn, enabled: year !== null && year !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof financeYear>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FinanceYearQueryResult = NonNullable<Awaited<ReturnType<typeof financeYear>>>
export type FinanceYearQueryError = unknown


export function useFinanceYear<TData = Awaited<ReturnType<typeof financeYear>>, TError = unknown>(
 year: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof financeYear>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof financeYear>>,
          TError,
          Awaited<ReturnType<typeof financeYear>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFinanceYear<TData = Awaited<ReturnType<typeof financeYear>>, TError = unknown>(
 year: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof financeYear>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof financeYear>>,
          TError,
          Awaited<ReturnType<typeof financeYear>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFinanceYear<TData = Awaited<ReturnType<typeof financeYear>>, TError = unknown>(
 year: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof financeYear>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFinanceYear<TData = Awaited<ReturnType<typeof financeYear>>, TError = unknown>(
 year: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof financeYear>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFinanceYearQueryOptions(year,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const listUnpaid = (

 options?: SecondParameter<typeof http>,signal?: AbortSignal
) => {


      return http<UnpaidItem[]>(
      {url: `/api/finance/unpaid`, method: 'GET', signal
    },
      options);
    }




export const getListUnpaidQueryKey = () => {
    return [
    `/api/finance/unpaid`
    ] as const;
    }


export const getListUnpaidQueryOptions = <TData = Awaited<ReturnType<typeof listUnpaid>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUnpaid>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUnpaidQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUnpaid>>> = ({ signal }) => listUnpaid(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUnpaid>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUnpaidQueryResult = NonNullable<Awaited<ReturnType<typeof listUnpaid>>>
export type ListUnpaidQueryError = unknown


export function useListUnpaid<TData = Awaited<ReturnType<typeof listUnpaid>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUnpaid>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUnpaid>>,
          TError,
          Awaited<ReturnType<typeof listUnpaid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUnpaid<TData = Awaited<ReturnType<typeof listUnpaid>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUnpaid>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUnpaid>>,
          TError,
          Awaited<ReturnType<typeof listUnpaid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUnpaid<TData = Awaited<ReturnType<typeof listUnpaid>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUnpaid>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListUnpaid<TData = Awaited<ReturnType<typeof listUnpaid>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUnpaid>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUnpaidQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
